### ISSUE TITLE
tags2sst breaking

### ISSUE THREAD

**Issue by muranava** [nschneid/pysupersensetagger#16]
hi

getting this message when running tags2sst:

----------
Traceback (most recent call last):
  File "src/tags2sst.py", line 203, in <module>
    convert(fileinput.input(args), labelsInRenderedAnno=labelsInRenderedAnno)
  File "src/tags2sst.py", line 191, in convert
    readsent()
  File "src/tags2sst.py", line 186, in readsent
    ({int(k): v[1] for k,v in data["labels"].items()} if labelsInRenderedAnno else {})), 
  File "src/tags2sst.py", line 103, in render
    return u''.join(sum(zip(before,ww,labelafter,after), ())).strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
------------

i get the .tags file generated correctly and the tags2sst works on the example file

**Comment by muranava** [comment]
hi removing u in line 103 seemed to have solved this issue

**Comment by nschneid** [comment]
Thanks. This is a reminder to myself to fix it in the repository.

**Comment by nschneid** [comment]
@muranava, does the version at https://github.com/nschneid/pysupersensetagger/blob/master/src/tags2sst.py fix the problem?

**Comment by muranava** [comment]
hi great thanks seems to work and the output is cleaner to work with as well for novices liek me :)
 


     On Tuesday, 14 April 2015, 11:17, nschneid <notifications@github.com> wrote:
   

 @muranava, does the version at https://github.com/nschneid/pysupersensetagger/blob/master/src/tags2sst.py fix the problem?—
