### ISSUE TITLE
Script to list MWEs in data

### ISSUE THREAD

**Issue by nschneid** [nschneid/pysupersensetagger#17]
(requested by @muranava)

**Comment by nschneid** [comment]
@muranava, I've added mwelist.py: does this meet your needs?

**Comment by muranava** [comment]
hitried it but getting this error:
----Traceback (most recent call last):
  File "src/mwelist.py", line 51, in <module>
    for (mwetype,strength),n in sorted(mwe_lemma_counts(fileinput.input(args), individual=individual).items()):
  File "src/mwelist.py", line 25, in mwe_lemma_counts
    sentId, anno, data = ln.strip().split('\t')
ValueError: need more than 2 values to unpack---
thanks
 


     On Tuesday, 14 April 2015, 12:47, nschneid <notifications@github.com> wrote:
   

 @muranava, I've added mwelist.py: does this meet your needs?—

**Comment by nschneid** [comment]
> hitried it but getting this error:
> ----Traceback (most recent call last):

...

>  File "src/mwelist.py", line 25, in mwe_lemma_counts
>    sentId, anno, data = ln.strip().split('\t')
> ValueError: need more than 2 values to unpack

What is the format of the file you are providing as input? It should be .sst or .mwe.

**Comment by muranava** [comment]
hi yes tried it on a .sst file, will have another go
 


     On Wednesday, 15 April 2015, 13:24, nschneid <notifications@github.com> wrote:
   

 
hitried it but getting this error:
----Traceback (most recent call last):
...
File "src/mwelist.py", line 25, in mwe_lemma_counts
 sentId, anno, data = ln.strip().split('\t')
ValueError: need more than 2 values to unpack
What is the format of the file you are providing as input? It should be .sst or .mwe.—

**Comment by muranava** [comment]
hi
tried it with the example.pred.sst and same error message 


     On Wednesday, 15 April 2015, 16:44, a b <navabcde1@yahoo.co.uk> wrote:
   

 hi yes tried it on a .sst file, will have another go
 


     On Wednesday, 15 April 2015, 13:24, nschneid <notifications@github.com> wrote:
   

 
hitried it but getting this error:
----Traceback (most recent call last):
...
File "src/mwelist.py", line 25, in mwe_lemma_counts
 sentId, anno, data = ln.strip().split('\t')
ValueError: need more than 2 values to unpack
What is the format of the file you are providing as input? It should be .sst or .mwe.—

**Comment by nschneid** [comment]
Ah sorry, it was breaking because the first column is empty (no sentence ID). Works now:

```
$ src/mwelist.py example.pred.sst
check out	_	1
draco malfoy	_	1
give grief	_	1
harry , ron	~	1
harry potter	_	1
hollywood studio	_	1
silver screen	_	1
so far	_	1
warner bros	_	1
```

**Comment by muranava** [comment]
hi Nathan
great thanks!
i was wondering if it would be straightforward to modify script to list lemmas is frequency order i.e. most frequent first?
i was having a look at script but can't see what to do!
sorry for all these demands!

 


     On Thursday, 16 April 2015, 14:13, nschneid <notifications@github.com> wrote:
   

 Ah sorry, it was breaking because the first column is empty (no sentence ID). Works now:$ src/mwelist.py example.pred.sst
check out   _   1
draco malfoy    _   1
give grief  _   1
harry , ron ~   1
harry potter    _   1
hollywood studio    _   1
silver screen   _   1
so far  _   1
warner bros _   1

**Comment by nschneid** [comment]
> i was wondering if it would be straightforward to modify script to list lemmas is frequency order i.e. most frequent first?

This can be done with the Unix `sort` command:

    $ src/mwelist.py data.sst > counts.tsv
    $ sort -t$'\t' -k3,3 -n -r counts.tsv

Or the TSV file can be opened in a spreadsheet application for sorting.

**Comment by muranava** [comment]
oh yes thank you :)
 


     On Saturday, 18 April 2015, 12:46, nschneid <notifications@github.com> wrote:
   

 
i was wondering if it would be straightforward to modify script to list lemmas is frequency order i.e. most frequent first?
This can be done with the Unix sort command:$ src/mwelist.py data.sst > counts.tsv
$ sort -t$'\t' -k3,3 -n -r counts.tsv
Or the TSV file can be opened in a spreadsheet application for sorting.—
